// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyPlanner.Infrastructure.Data;

#nullable disable

namespace WeeklyPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedEffort")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status", "Category");

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.CategoryAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BudgetHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "Category")
                        .IsUnique();

                    b.ToTable("CategoryAllocations");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.CycleMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("CycleId", "MemberId")
                        .IsUnique();

                    b.ToTable("CycleMembers");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.MemberPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPlannedHours")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("CycleId", "MemberId")
                        .IsUnique();

                    b.ToTable("MemberPlans");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.PlanningCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExecutionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExecutionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlanningCycles");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.ProgressUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NewHoursCompleted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PreviousHoursCompleted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskAssignmentId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ProgressUpdates");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CommittedHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursCompleted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MemberPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProgressStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("MemberPlanId");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLead")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.BacklogItem", b =>
                {
                    b.HasOne("WeeklyPlanner.Core.Entities.TeamMember", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByMember");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.CategoryAllocation", b =>
                {
                    b.HasOne("WeeklyPlanner.Core.Entities.PlanningCycle", "Cycle")
                        .WithMany("CategoryAllocations")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.CycleMember", b =>
                {
                    b.HasOne("WeeklyPlanner.Core.Entities.PlanningCycle", "Cycle")
                        .WithMany("CycleMembers")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Core.Entities.TeamMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.MemberPlan", b =>
                {
                    b.HasOne("WeeklyPlanner.Core.Entities.PlanningCycle", "Cycle")
                        .WithMany("MemberPlans")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Core.Entities.TeamMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.ProgressUpdate", b =>
                {
                    b.HasOne("WeeklyPlanner.Core.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Core.Entities.TeamMember", "UpdatedByMember")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaskAssignment");

                    b.Navigation("UpdatedByMember");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.TaskAssignment", b =>
                {
                    b.HasOne("WeeklyPlanner.Core.Entities.BacklogItem", "BacklogItem")
                        .WithMany()
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Core.Entities.MemberPlan", "MemberPlan")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("MemberPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacklogItem");

                    b.Navigation("MemberPlan");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.MemberPlan", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.PlanningCycle", b =>
                {
                    b.Navigation("CategoryAllocations");

                    b.Navigation("CycleMembers");

                    b.Navigation("MemberPlans");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Entities.TaskAssignment", b =>
                {
                    b.Navigation("ProgressUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
